tutorial level instructions
180D-FW-2021/Team2 pull request #69
Opened 2022-02-26 05:10 UTC by rachel92124

I added instructions in level 0 that appear based on where you are in the maze
LMK if there are instructions I should add/change. I'm not sure if I am specific enough in my instructions.

2022-02-26 06:09 UTC, sydneylaiw commented
Other than that, LGTM. Only thing is if possible, it might be nice to make the text bolder/in a diff color so it pops more against the maze background.

2022-02-26 20:40 UTC, anreeta commented
Tutorial level looks neat! Instead of making text a different color you could put the text on a Panel UI element with a semi-transparent background to make it stand out regardless of where in the level you are

Also, very minor but for some of the instructions, you could put a comma between after the "To jump/duck/etc" part

2022-03-03 00:15 UTC, sydneylaiw requested changes

2022-03-03 00:15 UTC, sydneylaiw commented on Unity/Assets/Scripts/TutorialInstructions.cs
> +            Show("To move forward use the arrow keys, WASD, or tilt the cotroller forward");
small typo: controller

2022-03-03 00:15 UTC, sydneylaiw commented on Unity/Assets/Scripts/TutorialInstructions.cs
> +            Show("To jump, press the space bar or lighly jump while in frame of your webcam");
*lightly, sorry didn't notice this the first time

2022-03-03 05:53 UTC, anreeta commented on Unity/Assets/Scripts/TutorialInstructions.cs
> +            Show("To turn, use 'z' and 'x' or tilt the controller left and right");
Very minor but maybe can say "To turn left and right, use 'z' and 'x' or tilt the controller"

Likely also fine as is

2022-03-03 05:53 UTC, anreeta commented
Have looked at the PR again. The semi-transparent background looks fine to me. 

One minor thing: there are apparently inconsistent line endings in TutorialInstructions.cs... maybe want to make them all LF?

Otherwise, after Sydney's changes, it looks good to merge

2022-03-04 20:30 UTC, merged